[package]
name = "wasip2-http-proxy-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.41.0"
wit-bindgen-rt = "0.41.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
